practiceproject/practiceapp/urls.py
from django.urls import path, re_path
from . import views

app_name = 'practiceapp'

urlpatterns = [

    path('', views.post_list_view),
    re_path(r'^tag/(?P<tag_slug>[-\w]+)/$', views.post_list_view, name='post_list_by_tag_name'),
    re_path(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',
            views.post_detail_view, name='post_detail'),
    re_path(r'^(?P<id>\d+)/share/$', views.mail_send_view),
]

practiceproject/practiceproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('practiceapp.urls',namespace='abcd')),
]

practiceproject/practiceapp/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
from taggit.managers import TaggableManager
# Create your models here.

class Post(models.Model):
    STATUS_CHOICES = (('draft','DRAFT'),('published','PUBLISHED'))
    title = models.CharField(max_length=264)
    slug= models.SlugField(max_length=264, unique_for_date='publish')
    author = models.ForeignKey(User,related_name='blog_posts',on_delete=models.CASCADE)
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    status = models.CharField(max_length=10,choices=STATUS_CHOICES)
    tags = TaggableManager()

    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('abcd:post_detail',args=[self.publish.year, self.publish.strftime('%m'),
                                               self.publish.strftime('%d'), self.slug])

class Comment(models.Model):

    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=32)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('created',)

    def __str__(self):
        return 'Commented By{} on {}'.format(self.name, self.post)

practiceproject/practiceapp/forms.py
from django import forms
from .models import Comment

class EmailSendForm(forms.Form):
    name=forms.CharField()
    email=forms.EmailField()
    to=forms.EmailField()
    comments=forms.CharField(required=False,widget=forms.Textarea)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name','email','body')

practiceproject/practiceapp/views.py
from django.shortcuts import render,get_object_or_404
from .models import Post
from .models import Comment
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.core.mail import send_mail
from .forms import EmailSendForm
from .forms import CommentForm
from taggit.models import Tag

def post_list_view(request,tag_slug=None):
    post_list = Post.objects.all()
    tag=None
    if tag_slug:
        tag=get_object_or_404(Tag,slug=tag_slug)
        post_list=post_list.filter(tags__in=[tag])

    paginator = Paginator(post_list,5)
    page_number = request.GET.get('page')
    try:
        post_list = paginator.page(page_number)
    except PageNotAnInteger:
       post_list = paginator.page(1)
    except EmptyPage:
        post_list = paginator.page(paginator.num_pages)
    return render(request,'temp1/post_list.html',{'post_list':post_list,'tag':tag})

def post_detail_view(request,year,month,day,post):
    post = get_object_or_404(Post,slug=post,
                             status='published',
                             publish__year=year,
                             publish__month=month,
                             publish__day=day)
    comments = post.comments.filter(active=True)
    csubmit=False
    if request.method == 'POST':
        form = CommentForm(data=request.POST)
        if form.is_valid():
            new_comment = form.save(commit=False)
            new_comment.post=post
            new_comment.save()
            csubmit=True
    else:
        form = CommentForm()

    return render(request,'temp1/post_detail.html',{'post':post,'form':form,'comments':comments,'csubmit':csubmit})


def mail_send_view(request,id):
    post = get_object_or_404(Post,id=id,status='published')
    sent=False
    if request.method=='POST':
       form = EmailSendForm(request.POST)
       if form.is_valid():
           cd = form.cleaned_data
           post_url = request.build_absolute_uri(post.get_absolute_url())
           subject = '{}({})recommends you to read"{}"'.format(cd['name'],cd['email'],post.title)
           message = 'Read Post At: \n{}\n\n{}\'Comments:\n{}'.format(post_url,cd['name'],cd['comments'])
           send_mail(subject,message,'jacksonmama0505@gmail.com',[cd['to']])
           sent = True
    else:
        form = EmailSendForm()
    return render(request,'temp1/sharebymail.html',{'post':post,'form':form,'sent':sent})

practiceproject/templates/temp1/base.html
<!DOCTYPE html>
{%load practice_tags%}
{%load static%}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
          integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
          crossorigin="anonymous">
    <link rel="stylesheet" href="{%static "css/practice.css"%}">
    <title>{%block title%}{%endblock%}</title>
</head>
<body>
    <div class="content">
        {%block content%}{%endblock%}
    </div>
    <div class="sidebar">
        <h2>DURGA'S Blog</h2>
        <p>The total number of published posts upto today: {%total_posts%}</p>
        <h3>Latest Posts:</h3>{%show_latest_posts 100%}
        
    </div>
</body>
</html>

practiceproject/templates/temp1/latest_posts123.html
<ul>
    {%for post in latest_posts%}
    <li><a href="{{post.get_absolute_url}}">{{post.title}}</a></li>
    {%endfor%}
</ul>

practiceproject/templates/temp1/pagination.html
<div class="paginator">
    <span>
        {%if page.has_previous%}
          <a href="?page={{page.previous_page_number}}">Previous</a>
        {%endif%}
    </span>
    <span>
        page {{page.number}} of {{page.paginator.num_pages}}
    </span>
    <span>
        {%if page.has_next%}
           <a href="?page={{page.next_page_number}}">Next</a>
        {%endif%}
    </span>
</div>

practiceproject/templates/temp1/post_detail.html
<!DOCTYPE html>
{%extends 'temp1/base.html'%}
{%block title%}{{post.title}}{%endblock%}
{%block content%}
    <h1>{{post.title}}</h1>
    <p id="date">Published on {{post.publish}} by {{post.author|title}}</p>
    {{post.body|linebreaks}}
    <a href="/{{post.id}}/share" class="btn btn-lg btn-primary">Share Post by Email</a>
    {%with comments.count as comments_count%}
    <h2>{{comments_count}} Comments{{Comments_count|pluralize}}</h2>
    {%endwith%}
    {%if comments%}
        {%for comment in comments%}
            <p id="co">Comment {{forloop.counter}} by {{comment.name}} on {{comment.created}}</p>
            <div class="cb">{{comment.body|linebreaks}}</div>
            <hr>
        {%endfor%}
        {%else%}
            <p>There are no comments yet!!!</p>
    {%endif%}
    {%if csubmit%}
        <h2>Your Comment Added Successfully</h2>
    {%else%}
    <form method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" class="btn btn-lg btn-primary" value="Submit Comment">
    </form>
    {%endif%}

{%endblock%}

practiceproject/templates/temp1/post_list.html
<!DOCTYPE html>
{%extends 'temp1/base.html'%}
{%block title%}DURGA'S BLOG{%endblock%}
{%block content%}
    <h1>DURGA's Blog</h1>
    {%for post in post_list%}
      <h2><a href="{{post.get_absolute_url}}">{{post.title}}</a></h2>
        <p>Tags:
            {%for tag in post.tags.all%}
            <a href="{%url 'practiceapp:post_list_by_tag_name' tag.slug%}">{{tag.name}}</a>
            {%if not forloop.last%},{%endif%}
            {%endfor%}
        </p>
        <p id="date">Published on {{post.publish}} by {{post.author|title}}</p>
        {{post.body | truncatewords:15}}
    {%endfor%}
{%include 'temp1/pagination.html' with page=post_list%}
{%endblock%}

practiceproject/templates/temp1/sharebymail.html
<!DOCTYPE html>
{%extends 'temp1/base.html'%}
{%block title%}Share Post by Email{%endblock%}
{%block content%}
    {%if sent%}
        <h1>Email Successfully Sent</h1>
        <p>"{{post.title}}" was sent by email</p>
    {%else%}
        <h1>Share {{post.title}}" by Email"</h1>
        <form method="post">
        {{form.as_p}}
        {%csrf_token%}
        <input type="submit" name="" class="btn btn-lg btn-success" value="Send Mail">
    </form>
    {%endif%}
{%endblock%}